name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: Install and Build
      run: |
        yarn install
        yarn build
        yarn export
        touch ./out/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
